{ ... }:

{
  # SwayOSD shows a translucent overlay for volume / brightness changes.
  # The CSS style is generated by Matugen into ~/.config/swayosd/style.css;
  # swayosd-server reads that path by default so no explicit stylePath needed.
  services.swayosd = {
    enable = true;
    topMargin = 0.9;
  };
}
